### ISSUE TITLE
roibuddy does not run in Linux because Qwt5 cannot be found

### ISSUE THREAD

**Issue by vjlbym** [losonczylab/roibuddy#17]
Hi, 
I followed the instructions on the ROIbuddy page to install PyQt4, PyQwt5, guidata and guiqwt on Ubuntu and all of them said "successfully installed". I can also uninstall and reinstall them, confirming that they are indeed installed. `pip install roibuddy` ran fine too. But when I run the executable, it gives the following error saing Qwt5 is not found. I understand that this might not be an issue with roibuddy but does anyone know how to fix this? I've tried uninstalling all of the above and reinstalling in sequence. Also, for installing PyQwt5, I used Ubuntu Trusty from http://packages.ubuntu.com/trusty/python-qwt5-qt4 by `apt-get install python-qwt5-qt4`. Any help is deeply appreciated. Thanks!

```
/home/stuberlab/anaconda/lib/python2.7/site-packages/skimage/filter/__init__.py:6: skimage_deprecation: The `skimage.filter` module has been renamed to `skimage.filters`.  This placeholder module will be removed in v0.13.
  warn(skimage_deprecation('The `skimage.filter` module has been renamed '
Traceback (most recent call last):
  File "/home/stuberlab/anaconda/bin/roibuddy", line 7, in <module>
    from roibuddy.roi_buddy import main
  File "/home/stuberlab/anaconda/lib/python2.7/site-packages/roibuddy/roi_buddy.py", line 34, in <module>
    import guiqwt.baseplot
  File "/home/stuberlab/anaconda/lib/python2.7/site-packages/guiqwt/baseplot.py", line 60, in <module>
    from guiqwt.transitional import (QwtPlot, QwtLinearScaleEngine,
  File "/home/stuberlab/anaconda/lib/python2.7/site-packages/guiqwt/transitional.py", line 19, in <module>
    from PyQt4.Qwt5 import (QwtPlot, QwtSymbol, QwtLinearScaleEngine,
ImportError: No module named Qwt5
```

**Comment by vjlbym** [comment]
Actually, update: I built Qwt5 from source rather than install a pre-built package. That worked. Thanks a lot!
