### ISSUE TITLE
ValueError: API 'QString'

### ISSUE THREAD

**Issue by mschottdorf** [losonczylab/roibuddy#21]
Hi, I recently tried to install roibuddy an two independent linux systems; a debian (as root) and on a suse (as user). Both times I succeeded in installing all required libraries

sima==1.3.0
guidata==1.7.3
guiqwt==3.0.1

but when trying to launch roibuddy, I get a ValueError from the QT API:

Traceback (most recent call last):
  File "/usr/local/bin/roibuddy", line 9, in <module>
    load_entry_point('roibuddy==1.0.0-dev', 'gui_scripts', 'roibuddy')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/local/lib/python2.7/dist-packages/roibuddy-1.0.0_dev-py2.7.egg/roibuddy/roi_buddy.py", line 31, in <module>
    from guidata import qthelpers
  File "/usr/local/lib/python2.7/dist-packages/guidata-1.7.3-py2.7.egg/guidata/**init**.py", line 541, in <module>
    import guidata.config
  File "/usr/local/lib/python2.7/dist-packages/guidata-1.7.3-py2.7.egg/guidata/config.py", line 15, in <module>
    from guidata.configtools import add_image_module_path, get_translation
  File "/usr/local/lib/python2.7/dist-packages/guidata-1.7.3-py2.7.egg/guidata/configtools.py", line 22, in <module>
    from guidata.qt.QtGui import (QFont, QLabel, QPixmap, QIcon, QHBoxLayout,
  File "/usr/local/lib/python2.7/dist-packages/guidata-1.7.3-py2.7.egg/guidata/qt/**init**.py", line 25, in <module>
    sip.setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1

I guess that guidata and roibuddyt a different qt api. Is this the case? I have no ideas how to fix this. Any ideas?

running python directly, I can import roibuddy
In [1]: import roibuddy
In [2]: roibuddy.
roibuddy.QtCore        roibuddy.QtGui         roibuddy.Ui_ROI_Buddy  roibuddy.roiBuddyUI

**Comment by angelc134** [comment]
Your guidata and guidata packages need to be downgraded. Use guidata==1.6.1 and guiqwt==2.3.1, that should resolve your issue.

**Comment by mschottdorf** [comment]
Hi Folks, 

Thanks for the quick answer!  I changed the versions to 
pip freeze | grep gui
guidata==1.6.1
guiqwt==2.3.1

But the version of guidata makes problems:

manuel@adugak ~ $ roibuddy 
Traceback (most recent call last):
  File "/usr/local/bin/roibuddy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (guidata 1.6.1 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('guidata>=1.7.0'))

Any further advise?

Thanks!
Manuel

---

I had several versions installed, and setting the paths properly resolved this problem

**Comment by angelc134** [comment]
Great! Sorry for not replying back sooner

**Comment by PierreRaybaut** [comment]
PR https://github.com/losonczylab/roibuddy/pull/23 solves (at least maybe only partially for now) this issue.
